spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQL_PORT}/carwash?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    carwash: ${EMAIL:carwash1303@gmail.com}
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:carwash1303@gmail.com}
    password: ${EMAIL_PASSWORD:nbmpndmvsjofuvqv}

  remember:
    key: ${REMEMBER_KEY:carwash}
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}


#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
